baseURL = 'https://incomparable-strudel-63ad22.netlify.app/'
title = "Prakash's Blog"
theme = "bootstrap"
# Pagination
paginate = 5
# paginatePath = "page"
copyright = "Copyright © 2020-{year} Prakash Bhandari. All Rights Reserved."

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = ""

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[build]
  writeStats = true


